# Generated by Django 2.2.15 on 2022-05-14 04:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair')], max_length=100)),
                ('brand', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('postJavascript', models.CharField(blank=True, max_length=5000)),
                ('postImageUrl', models.CharField(blank=True, max_length=2000)),
                ('postADUrl', models.CharField(blank=True, max_length=2000)),
                ('postADClickCount', models.IntegerField(blank=True, null=True)),
                ('postADClickPerEarn', models.DecimalField(decimal_places=5, default=0, max_digits=9)),
                ('postADTotalEarn', models.DecimalField(decimal_places=5, default=0, max_digits=9)),
                ('postADReceivePaymentMethod', models.CharField(blank=True, max_length=50)),
                ('postADPaymentReceiveAccount', models.CharField(blank=True, max_length=1000)),
                ('postADPaymentTotalReceived', models.DecimalField(decimal_places=5, default=0, max_digits=9)),
                ('postADPaymentReceiveable', models.DecimalField(decimal_places=5, default=0, max_digits=9)),
                ('postADPaymentReceiveStatus', models.CharField(blank=True, max_length=50)),
                ('postADPaymentLatestReceiveDate', models.DateTimeField(blank=True, null=True)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Classified Ads',
            },
        ),
        migrations.CreateModel(
            name='AdsBottomBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Place Your Ad', max_length=200)),
                ('image', models.ImageField(default=None, upload_to='banners/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='AdsRightBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Place Your Ad', max_length=200)),
                ('image', models.ImageField(default=None, upload_to='banners/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='AdsTopBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Place Your Ad', max_length=200)),
                ('image', models.ImageField(default=None, upload_to='banners/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='uploads/category')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'country',
            },
        ),
        migrations.CreateModel(
            name='postADViewerIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postADViewerIP_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Poster AD Viewers IPs',
            },
        ),
        migrations.CreateModel(
            name='postIPaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postIPaddress_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Poster IP address',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default-profile-pic.png', null=True, upload_to='uploads/profile-pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdViewerActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdID', models.IntegerField(blank=True, null=True)),
                ('viewerIP', models.CharField(blank=True, max_length=50)),
                ('viewerCountry', models.CharField(blank=True, max_length=50)),
                ('viewerState', models.CharField(blank=True, max_length=50)),
                ('viewerCity', models.CharField(blank=True, max_length=50)),
                ('viewerZip', models.CharField(blank=True, max_length=50)),
                ('viewerTimezone', models.CharField(blank=True, max_length=50)),
                ('viewerIsp', models.CharField(blank=True, max_length=50)),
                ('viewerLat', models.CharField(blank=True, max_length=50)),
                ('viewerLon', models.CharField(blank=True, max_length=50)),
                ('viewerViewTime', models.DateTimeField(blank=True, null=True)),
                ('viewerViewDuration', models.DateTimeField(blank=True, null=True)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Ads')),
            ],
            options={
                'verbose_name_plural': 'Ad Viewer Activity',
            },
        ),
        migrations.CreateModel(
            name='AdsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='uploads/%Y/%m/%d')),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Ads')),
            ],
            options={
                'verbose_name_plural': 'Classified Ads Images',
            },
        ),
        migrations.AddField(
            model_name='ads',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.Author'),
        ),
        migrations.AddField(
            model_name='ads',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.Category'),
        ),
        migrations.AddField(
            model_name='ads',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.City'),
        ),
        migrations.AddField(
            model_name='ads',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.country'),
        ),
        migrations.AddField(
            model_name='ads',
            name='postADViewerIP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.postADViewerIP'),
        ),
        migrations.AddField(
            model_name='ads',
            name='postIPaddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.postIPaddress'),
        ),
        migrations.AddField(
            model_name='ads',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.State'),
        ),
    ]
