# Generated by Django 2.2.15 on 2022-05-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='postADMaxEarn',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=9),
        ),
    ]
