# Generated by Django 2.2.15 on 2022-05-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ads_adpostby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='adPostBy',
            field=models.CharField(choices=[('Superuser', 'Superuser'), ('Author', 'Author'), ('AutoAssigned', 'AutoAssigned')], max_length=100),
        ),
    ]
