# Generated by Django 2.2.15 on 2022-05-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20220518_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='advieweractivity',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.Author'),
        ),
    ]
